import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "./components/Sidebar";
import ActionBar from "./components/ActionBar";
import { DataContextProvider } from "./context/DataContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <DataContextProvider>
          <div className="flex w-screen h-auto items-top bg-neutral-950">
            <Sidebar />
            <main className="w-4/6">{children}</main>
            <ActionBar />
          </div>
        </DataContextProvider>
      </body>
    </html>
  );
}
